export { LoginPage } from './login'
export { RegisterPage } from './register'
export { ChatsPageConnect } from './chats'
export { ProfilePageConnect } from './profile'
export { ProfileEditPageConnect } from './profileEdit'
export { ProfilePasswordPage } from './profilePassword'
export { ErrorPage } from './error'
