export { LoginPage } from './login'
export { RegisterPage } from './register'
export { ChatsPage } from './chats'
export { ProfilePage } from './profile'
export { ProfileEditPage } from './profileEdit'
export { ProfilePasswordPage } from './profilePassword'
export { ChangeAvatarPage } from './changeAvatar'
export { ErrorPage } from './error'
